#!/usr/bin/python3

# The key_event_name refers to {}/keyboard/_canonical_names.py 
KEY_EVENT_NAME_LEFT = 'left'
KEY_EVENT_NAME_RIGHT = 'right'
KEY_EVENT_NAME_UP = 'up'
KEY_EVENT_NAME_DOWN = 'down'
KEY_EVENT_NAME_SEL = 'enter'
KEY_EVENT_NAME_HELP = 'help'
KEY_EVENT_NAME_F14 = 'f14'
KEY_EVENT_NAME_TIVO = 'tivo'
KEY_EVENT_NAME_VOICE = 'voice'
KEY_EVENT_NAME_APPS = 'apps'
KEY_EVENT_NAME_MUTE = 'mute'
KEY_EVENT_NAME_VOLUP = KEY_EVENT_NAME_HELP
KEY_EVENT_NAME_VOLDW = KEY_EVENT_NAME_F14
KEY_EVENT_NAME_POWER = 'power'
KEY_EVENT_NAME_BACK = 'backspace'
KEY_EVENT_NAME_0 = '0'
KEY_EVENT_NAME_1 = '1'
KEY_EVENT_NAME_2 = '2'
KEY_EVENT_NAME_3 = '3'
KEY_EVENT_NAME_4 = '4'
KEY_EVENT_NAME_5 = '5'
KEY_EVENT_NAME_6 = '6'
KEY_EVENT_NAME_7 = '7'
KEY_EVENT_NAME_8 = '8'
KEY_EVENT_NAME_9 = '9'
