HID_REPORT_VALUES = 'HID_REPORT_VALUES'
KEY_TABLE = 'KEY_TABLE'
HID_REPORTS = 'HID_REPORTS'
REPORT_NAME = 'REPORT_NAME'
REPORT_ID = 'REPORT_ID'
REPORT_LENGTH = 'REPORT_LENGTH'

# Key Table
REFER_TO_HID_REPORT = 'REFER_TO_HID_REPORT'
KEY_CODE = 'KEY_CODE'