# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tivo_rcu.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TivoRcuDlg(object):
    def setupUi(self, TivoRcuDlg):
        TivoRcuDlg.setObjectName("TivoRcuDlg")
        TivoRcuDlg.resize(389, 660)
        self.KEY_RIGHT = QtWidgets.QPushButton(TivoRcuDlg)
        self.KEY_RIGHT.setGeometry(QtCore.QRect(180, 70, 31, 31))
        self.KEY_RIGHT.setAutoRepeatDelay(306)
        self.KEY_RIGHT.setObjectName("KEY_RIGHT")
        self.KEY_LEFT = QtWidgets.QPushButton(TivoRcuDlg)
        self.KEY_LEFT.setGeometry(QtCore.QRect(80, 70, 31, 31))
        self.KEY_LEFT.setAutoRepeatDelay(306)
        self.KEY_LEFT.setObjectName("KEY_LEFT")
        self.KEY_UP = QtWidgets.QPushButton(TivoRcuDlg)
        self.KEY_UP.setGeometry(QtCore.QRect(130, 20, 31, 31))
        self.KEY_UP.setAutoRepeatDelay(306)
        self.KEY_UP.setObjectName("KEY_UP")
        self.KEY_DOWN = QtWidgets.QPushButton(TivoRcuDlg)
        self.KEY_DOWN.setGeometry(QtCore.QRect(130, 120, 31, 31))
        self.KEY_DOWN.setAutoRepeatDelay(306)
        self.KEY_DOWN.setObjectName("KEY_DOWN")
        self.KEY_SEL = QtWidgets.QPushButton(TivoRcuDlg)
        self.KEY_SEL.setGeometry(QtCore.QRect(130, 70, 31, 31))
        self.KEY_SEL.setAutoRepeatDelay(306)
        self.KEY_SEL.setObjectName("KEY_SEL")
        self.KEY_1 = QtWidgets.QPushButton(TivoRcuDlg)
        self.KEY_1.setGeometry(QtCore.QRect(110, 410, 41, 41))
        self.KEY_1.setAutoRepeatDelay(306)
        self.KEY_1.setObjectName("KEY_1")
        self.KEY_2 = QtWidgets.QPushButton(TivoRcuDlg)
        self.KEY_2.setGeometry(QtCore.QRect(170, 410, 41, 41))
        self.KEY_2.setAutoRepeatDelay(306)
        self.KEY_2.setObjectName("KEY_2")
        self.KEY_3 = QtWidgets.QPushButton(TivoRcuDlg)
        self.KEY_3.setGeometry(QtCore.QRect(230, 410, 41, 41))
        self.KEY_3.setAutoRepeatDelay(306)
        self.KEY_3.setObjectName("KEY_3")
        self.KEY_6 = QtWidgets.QPushButton(TivoRcuDlg)
        self.KEY_6.setGeometry(QtCore.QRect(230, 460, 41, 41))
        self.KEY_6.setAutoRepeatDelay(306)
        self.KEY_6.setObjectName("KEY_6")
        self.KEY_4 = QtWidgets.QPushButton(TivoRcuDlg)
        self.KEY_4.setGeometry(QtCore.QRect(110, 460, 41, 41))
        self.KEY_4.setAutoRepeatDelay(306)
        self.KEY_4.setObjectName("KEY_4")
        self.KEY_5 = QtWidgets.QPushButton(TivoRcuDlg)
        self.KEY_5.setGeometry(QtCore.QRect(170, 460, 41, 41))
        self.KEY_5.setAutoRepeatDelay(306)
        self.KEY_5.setObjectName("KEY_5")
        self.KEY_9 = QtWidgets.QPushButton(TivoRcuDlg)
        self.KEY_9.setGeometry(QtCore.QRect(230, 510, 41, 41))
        self.KEY_9.setAutoRepeatDelay(306)
        self.KEY_9.setObjectName("KEY_9")
        self.KEY_7 = QtWidgets.QPushButton(TivoRcuDlg)
        self.KEY_7.setGeometry(QtCore.QRect(110, 510, 41, 41))
        self.KEY_7.setAutoRepeatDelay(306)
        self.KEY_7.setObjectName("KEY_7")
        self.KEY_8 = QtWidgets.QPushButton(TivoRcuDlg)
        self.KEY_8.setGeometry(QtCore.QRect(170, 510, 41, 41))
        self.KEY_8.setAutoRepeatDelay(306)
        self.KEY_8.setObjectName("KEY_8")
        self.KEY_0 = QtWidgets.QPushButton(TivoRcuDlg)
        self.KEY_0.setGeometry(QtCore.QRect(170, 560, 41, 41))
        self.KEY_0.setAutoRepeatDelay(306)
        self.KEY_0.setObjectName("KEY_0")
        self.KEY_BACK = QtWidgets.QPushButton(TivoRcuDlg)
        self.KEY_BACK.setGeometry(QtCore.QRect(80, 130, 31, 31))
        self.KEY_BACK.setAutoRepeatDelay(306)
        self.KEY_BACK.setObjectName("KEY_BACK")
        self.KEY_VOLDW = QtWidgets.QPushButton(TivoRcuDlg)
        self.KEY_VOLDW.setGeometry(QtCore.QRect(20, 110, 31, 51))
        self.KEY_VOLDW.setAutoRepeatDelay(306)
        self.KEY_VOLDW.setObjectName("KEY_VOLDW")
        self.KEY_VOLUP = QtWidgets.QPushButton(TivoRcuDlg)
        self.KEY_VOLUP.setGeometry(QtCore.QRect(20, 50, 31, 51))
        self.KEY_VOLUP.setAutoRepeatDelay(306)
        self.KEY_VOLUP.setObjectName("KEY_VOLUP")
        self.KEY_CHANNELDW = QtWidgets.QPushButton(TivoRcuDlg)
        self.KEY_CHANNELDW.setGeometry(QtCore.QRect(240, 110, 31, 51))
        self.KEY_CHANNELDW.setAutoRepeatDelay(306)
        self.KEY_CHANNELDW.setObjectName("KEY_CHANNELDW")
        self.KEY_CHANNELUP = QtWidgets.QPushButton(TivoRcuDlg)
        self.KEY_CHANNELUP.setGeometry(QtCore.QRect(240, 40, 31, 51))
        self.KEY_CHANNELUP.setAutoRepeatDelay(306)
        self.KEY_CHANNELUP.setObjectName("KEY_CHANNELUP")
        self.KEY_TIVO = QtWidgets.QPushButton(TivoRcuDlg)
        self.KEY_TIVO.setGeometry(QtCore.QRect(120, 160, 41, 41))
        self.KEY_TIVO.setAutoRepeatDelay(306)
        self.KEY_TIVO.setObjectName("KEY_TIVO")
        self.KEY_POWER = QtWidgets.QPushButton(TivoRcuDlg)
        self.KEY_POWER.setGeometry(QtCore.QRect(20, 10, 31, 31))
        self.KEY_POWER.setIconSize(QtCore.QSize(12, 12))
        self.KEY_POWER.setAutoRepeatDelay(306)
        self.KEY_POWER.setObjectName("KEY_POWER")
        self.info = QtWidgets.QLabel(TivoRcuDlg)
        self.info.setGeometry(QtCore.QRect(90, 630, 231, 20))
        font = QtGui.QFont()
        font.setBold(True)
        self.info.setFont(font)
        self.info.setObjectName("info")
        self.KEY_VOICE = QtWidgets.QPushButton(TivoRcuDlg)
        self.KEY_VOICE.setGeometry(QtCore.QRect(180, 160, 51, 41))
        self.KEY_VOICE.setAutoRepeatDelay(306)
        self.KEY_VOICE.setObjectName("KEY_VOICE")
        self.mCkbCaptureKeyboard = QtWidgets.QCheckBox(TivoRcuDlg)
        self.mCkbCaptureKeyboard.setGeometry(QtCore.QRect(110, 600, 151, 23))
        self.mCkbCaptureKeyboard.setObjectName("mCkbCaptureKeyboard")
        self.mLbPathTo8k = QtWidgets.QLabel(TivoRcuDlg)
        self.mLbPathTo8k.setGeometry(QtCore.QRect(100, 290, 251, 31))
        self.mLbPathTo8k.setObjectName("mLbPathTo8k")
        self.mLbPathTo16k = QtWidgets.QLabel(TivoRcuDlg)
        self.mLbPathTo16k.setGeometry(QtCore.QRect(100, 360, 261, 31))
        self.mLbPathTo16k.setObjectName("mLbPathTo16k")
        self.groupBox = QtWidgets.QGroupBox(TivoRcuDlg)
        self.groupBox.setGeometry(QtCore.QRect(40, 260, 331, 71))
        self.groupBox.setObjectName("groupBox")
        self.mBtnOpen8k = QtWidgets.QPushButton(self.groupBox)
        self.mBtnOpen8k.setGeometry(QtCore.QRect(10, 30, 41, 31))
        self.mBtnOpen8k.setObjectName("mBtnOpen8k")
        self.groupBox_2 = QtWidgets.QGroupBox(TivoRcuDlg)
        self.groupBox_2.setGeometry(QtCore.QRect(40, 330, 331, 71))
        self.groupBox_2.setObjectName("groupBox_2")
        self.mBtnOpen16k = QtWidgets.QPushButton(self.groupBox_2)
        self.mBtnOpen16k.setGeometry(QtCore.QRect(10, 30, 41, 31))
        self.mBtnOpen16k.setObjectName("mBtnOpen16k")
        self.mRdCaptureVoice = QtWidgets.QRadioButton(TivoRcuDlg)
        self.mRdCaptureVoice.setGeometry(QtCore.QRect(20, 200, 141, 23))
        self.mRdCaptureVoice.setObjectName("mRdCaptureVoice")
        self.mRdCaptureFile = QtWidgets.QRadioButton(TivoRcuDlg)
        self.mRdCaptureFile.setGeometry(QtCore.QRect(20, 230, 121, 23))
        self.mRdCaptureFile.setObjectName("mRdCaptureFile")
        self.groupBox_2.raise_()
        self.groupBox.raise_()
        self.KEY_RIGHT.raise_()
        self.KEY_LEFT.raise_()
        self.KEY_UP.raise_()
        self.KEY_DOWN.raise_()
        self.KEY_SEL.raise_()
        self.KEY_1.raise_()
        self.KEY_2.raise_()
        self.KEY_3.raise_()
        self.KEY_6.raise_()
        self.KEY_4.raise_()
        self.KEY_5.raise_()
        self.KEY_9.raise_()
        self.KEY_7.raise_()
        self.KEY_8.raise_()
        self.KEY_0.raise_()
        self.KEY_BACK.raise_()
        self.KEY_VOLDW.raise_()
        self.KEY_VOLUP.raise_()
        self.KEY_CHANNELDW.raise_()
        self.KEY_CHANNELUP.raise_()
        self.KEY_TIVO.raise_()
        self.KEY_POWER.raise_()
        self.info.raise_()
        self.KEY_VOICE.raise_()
        self.mCkbCaptureKeyboard.raise_()
        self.mLbPathTo8k.raise_()
        self.mLbPathTo16k.raise_()
        self.mRdCaptureVoice.raise_()
        self.mRdCaptureFile.raise_()

        self.retranslateUi(TivoRcuDlg)
        QtCore.QMetaObject.connectSlotsByName(TivoRcuDlg)

    def retranslateUi(self, TivoRcuDlg):
        _translate = QtCore.QCoreApplication.translate
        TivoRcuDlg.setWindowTitle(_translate("TivoRcuDlg", "Tivo RCU"))
        self.KEY_RIGHT.setText(_translate("TivoRcuDlg", "→"))
        self.KEY_LEFT.setText(_translate("TivoRcuDlg", "←"))
        self.KEY_UP.setText(_translate("TivoRcuDlg", "↑"))
        self.KEY_DOWN.setText(_translate("TivoRcuDlg", "↓"))
        self.KEY_SEL.setText(_translate("TivoRcuDlg", "Ok"))
        self.KEY_1.setText(_translate("TivoRcuDlg", "1"))
        self.KEY_2.setText(_translate("TivoRcuDlg", "2"))
        self.KEY_3.setText(_translate("TivoRcuDlg", "3"))
        self.KEY_6.setText(_translate("TivoRcuDlg", "6"))
        self.KEY_4.setText(_translate("TivoRcuDlg", "4"))
        self.KEY_5.setText(_translate("TivoRcuDlg", "5"))
        self.KEY_9.setText(_translate("TivoRcuDlg", "9"))
        self.KEY_7.setText(_translate("TivoRcuDlg", "7"))
        self.KEY_8.setText(_translate("TivoRcuDlg", "8"))
        self.KEY_0.setText(_translate("TivoRcuDlg", "0"))
        self.KEY_BACK.setText(_translate("TivoRcuDlg", "↺"))
        self.KEY_VOLDW.setText(_translate("TivoRcuDlg", "↓vol"))
        self.KEY_VOLUP.setText(_translate("TivoRcuDlg", "↑vol"))
        self.KEY_CHANNELDW.setText(_translate("TivoRcuDlg", "↓ch"))
        self.KEY_CHANNELUP.setText(_translate("TivoRcuDlg", "↑ch"))
        self.KEY_TIVO.setText(_translate("TivoRcuDlg", "Tivo"))
        self.KEY_POWER.setText(_translate("TivoRcuDlg", "P"))
        self.info.setText(_translate("TivoRcuDlg", "Press keyboard \"Esc\" to exit .."))
        self.KEY_VOICE.setText(_translate("TivoRcuDlg", "Voice"))
        self.mCkbCaptureKeyboard.setText(_translate("TivoRcuDlg", "Capture Keyboard"))
        self.mLbPathTo8k.setText(_translate("TivoRcuDlg", "path to 8k"))
        self.mLbPathTo16k.setText(_translate("TivoRcuDlg", "path to 16k"))
        self.groupBox.setTitle(_translate("TivoRcuDlg", "specify 8K file"))
        self.mBtnOpen8k.setText(_translate("TivoRcuDlg", "open"))
        self.groupBox_2.setTitle(_translate("TivoRcuDlg", "spcify 16k file"))
        self.mBtnOpen16k.setText(_translate("TivoRcuDlg", "open"))
        self.mRdCaptureVoice.setText(_translate("TivoRcuDlg", "Capture by voice"))
        self.mRdCaptureFile.setText(_translate("TivoRcuDlg", "Capture by file"))
